# Generated by Django 5.1.6 on 2025-03-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlistitems',
            old_name='user_id',
            new_name='user',
        ),
    ]
