# Generated by Django 5.1.6 on 2025-03-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_user_id_token_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistitems',
            name='symbol_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistitems',
            name='symbol_name',
            field=models.CharField(max_length=500),
        ),
    ]
