# Generated by Django 5.1.6 on 2025-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSecurity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_data', models.JSONField(blank=True, null=True)),
                ('broker_name', models.CharField(max_length=500)),
                ('symbol_name', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
